
if (!window.__TEMPLATE_BUNDLE) window.__TEMPLATE_BUNDLE = {};
window.__TEMPLATE_BUNDLE["/cms/widgets/Carousel.xhtml"] = "<hbox xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\">\n    \n    <hbox anon-id=\"imageContainer\"><\/hbox>\n    <span anon-id=\"previousButton\"><icon class=\"chevron-left\"><\/icon><\/span>\n    <span anon-id=\"nextButton\"><icon class=\"chevron-right\"><\/icon><\/span>\n    <hbox anon-id=\"statusContainer\" class=\"Hidden\"><\/hbox>\n<\/hbox>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/MobileCombinedNavigation.xhtml"] = "<div xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\">\n    \n    <div anon-id=\"menuButton\"><icon class=\"menu\"><\/icon><\/div>\n    <div anon-id=\"menuContainer\">\n    <\/div>\n<\/div>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/MobileHeader.xhtml"] = "<div xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\">\n    \n    <a anon-id=\"logoLink\">\n        <span anon-id=\"logoContainer\">\n            <img anon-id=\"logoImage\" alt=\"\" \/>\n        <\/span>\n        <h1 anon-id=\"teamName\"><\/h1>\n    <\/a>\n    <div anon-id=\"toolBox\">\n        <hbox anon-id=\"actionsContainer\">\n            <div anon-id=\"accountInfoContainer\"><\/div>\n            <div anon-id=\"toolItemsContainer\"><\/div>\n        <\/hbox>\n        <div anon-id=\"menuButton\"><icon class=\"menu\"><\/icon><\/div>\n    <\/div>\n    <div anon-id=\"menuContainer\">\n        <div anon-id=\"menuContainerInner\">\n            <div anon-id=\"menuHeader\">\n\n            <\/div>\n            <div anon-id=\"menuContent\">\n\n            <\/div>\n            <div anon-id=\"menuFooter\">\n\n            <\/div>\n        <\/div>\n    <\/div>\n<\/div>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/ReviewShowcase.xhtml"] = "<vbox xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\" >\n    \n    <vbox anon-id=\"busyIndicator\" class=\"BusyIndicator\" flex=\"1\">\n        <hbox><icon class=\"image-filter-tilt-shift\"><\/icon><span anon-id=\"loadingMessage\">Loading...<\/span><\/hbox>\n    <\/vbox>\n    <vbox anon-id=\"slideShowContainer\" flex=\"1\">\n    <\/vbox>\n<\/vbox>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/SignInInfoDialog.xhtml"] = "<vbox xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\" >\n    \n    <vbox class=\"Box\" flex=\"1\">\n        <div class=\"Description\">\n            <span anon-id=\"descriptionText\"><\/span>\n            <span class=\"Actions\" anon-id=\"actionsContainer\">\n                <a anon-id=\"contactTeam\">Contact your administrator<\/a> or\n                <a anon-id=\"signinOther\">sign in with a registered account<\/a> to continue.\n            <\/span>\n        <\/div>\n        <button anon-id=\"okButton\" type=\"button\" >OK<\/button>\n    <\/vbox>\n    <hbox class=\"ContactUsBox\" anon-id=\"contactUsBox\">\n        Question?<a anon-id=\"contactTeam2\"><\/a>\n    <\/hbox>\n<\/vbox>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/SignInNotificationDialog.xhtml"] = "<vbox xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\">\n    \n    <vbox class=\"Box\" flex=\"1\">\n        <vbox class=\"Entry\">\n            <span anon-id=\"titleText\">Welcome to {TEAM_NAME}<\/span>\n        <\/vbox>\n        <vbox class=\"Entry\">\n            <label>Have an existing account?<\/label>\n            <button anon-id=\"signinButton\" type=\"button\" >Sign in<\/button>\n        <\/vbox>\n        <vbox class=\"Entry\">\n            <label anon-id=\"actionsTitle\">New to {TEAM_NAME}?<\/label>\n            <vbox anon-id=\"actionsBox\" class=\"Actions ShowClass\">\n                <a class=\"Action\" anon-id=\"classRegistrationButton\">Continue to Class Selection<\/a>\n                <a class=\"Action\" anon-id=\"bookingRegistrationButton\">Continue to Booking Selection<\/a>\n                <a class=\"Action\" anon-id=\"teamRegistrationButton\">Continue to Comp<\/a>\n            <\/vbox>\n        <\/vbox>\n        <vbox class=\"Entry ContactBox\">\n            <span>Questions? <a anon-id=\"contactTeam\">Click here to contact {TEAM_NAME}<\/a><\/span>\n        <\/vbox>\n    <\/vbox>\n<\/vbox>\n";

window.__TEMPLATE_BUNDLE["/cms/widgets/UpcomingEvents.xhtml"] = "<box xmlns:ui=\"http:\/\/evolus.vn\/Namespaces\/WebUI\/1.0\" >\n    \n    <box anon-id=\"sidePane\">\n        <box anon-id=\"selectorPanes\">\n        <\/box>\n    <\/box>\n    <vbox anon-id=\"contentPane\">\n        <h3 anon-id=\"categoryHeader\"><\/h3>\n        <vbox anon-id=\"busyIndicator\" class=\"BusyIndicator\" flex=\"1\">\n            <hbox><icon class=\"image-filter-tilt-shift\"><\/icon><span anon-id=\"loadingMessage\">Loading...<\/span><\/hbox>\n        <\/vbox>\n        <ui:RepeaterView anon-id=\"eventList\" tag=\"div\" flex=\"1\">\n            <div class=\"Item\" role=\"item\" >\n                <div class=\"Calendar\">\n                    <span class=\"Month\" anon-id=\"month\">Jul<\/span>\n                    <div class=\"EventDateInfo\">\n                        <span class=\"Day\" anon-id=\"startDate\">20<\/span>\n                        <span class=\"Day\" anon-id=\"endDate\">23<\/span>\n                    <\/div>\n                    <span class=\"Year\" anon-id=\"year\">2018<\/span>\n                <\/div>\n                <div class=\"ContentWrapper\" flex=\"1\">\n                    <div class=\"Content\">\n                        <a href=\"#\" target=\"_self\" class=\"Title\" anon-id=\"title\"><\/a>\n                        <label class=\"Title\" anon-id=\"titleLabel\"><\/label>\n                        <vbox class=\"InfoDataContainer\" anon-id=\"infoDataContainer\"><\/vbox>\n                    <\/div>\n                    <div anon-id=\"actionContainer\" class=\"Actions\"><\/div>\n                <\/div>\n            <\/div>\n        <\/ui:RepeaterView>\n        <div anon-id=\"footerActions\">\n            <a href=\"#\" anon-id=\"moreCalendarLink\">View Events<\/a>\n        <\/div>\n    <\/vbox>\n<\/box>\n";

